export const TRACKS_REQUEST = "TRACKS_REQUEST"
export const TRACKS_SUCCESS = "TRACKS_SUCCESS"
export const TRACKS_ERROR = "TRACKS_ERROR"

export const PLAYER_NEW = "PLAYER_NEW"

export const PLAYLIST_SET = "PLAYLIST_SET"
export const PLAYLIST_CLEAR = "PLAYLIST_CLEAR"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "TLOGIN_FAILURE"
export const LOGOUT = "LOGOUT"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"
